### ISSUE TITLE
why deleted ogar-unlimited-autoinstall

### ISSUE THREAD

**Issue by NoiseControllers** [systemroot/sudo#1]
I feel having to communicate by this route

It was very useful

https://github.com/systemroot/ogar-unlimited-autoinstall

**Comment by systemroot** [comment]
I'm sorry but i'm out, from OGAR. 
To make that script available here was needed to update files every release of Ogar-Unlimited. 
So after this https://github.com/AJS-development/Ogar-unlimited/issues/1109
> Well. If you think i have make any modification about Statistics. Started from now i'll not add any of my server/s in statistics.. 
I have not do anythink to add my server/s on'top as you think or as that person which has raport me think. because i don't care about this i'm not 10 years old i'm 21. I have open those server just for fun to play some times because i can't play agar anymore.
and If i find an way to edit your plugin or anythink else i'll tell you look dude fix your plugin because i found this problem.

 i delete my private server's all and i run away from ogar. !
If you want to create one like that, you can create without any problem :smiley:  If you want help tell me.

**Comment by NoiseControllers** [comment]
you can pass files? for me

**Comment by systemroot** [comment]
@NoiseControllers 
![](http://image.prntscr.com/image/4e7872e00fe343dba8818bc596989f30.png)
Accept it and update README files put repo link 

And when ogar-unlimited will release a new version you will need to update 2 files.
**/settings/advConfig.ini**
and 
**core/ConfigService.js**
Go at Ogar-unlimited official repo, open those files in RAW , copy all find where is port 
`443` replace it with $2
and port ``88`` replace it with $3

and in ogar-unlimited-autoinstall you will need to update all **create.sh** 
find where i have wrote "advconfg" and  "ConfigService"
and replace them
![](http://image.prntscr.com/image/b8079c953b584422aea199199c6bd5b4.png)
and don't delete that **EOF** 
![](http://image.prntscr.com/image/e0f7e29176434c31aea61b257f194cfc.png)
